-- ============================================================
-- supabase_schema.sql
-- Generated from chemquest/prisma/schema.prisma
-- Target: Supabase (PostgreSQL 15+) — public schema
-- ============================================================
--
-- MAPPING NOTES & FOLLOW-UPS
-- ------------------------------------------------------------------
-- 1. ID columns (@id @default(cuid())) → text PRIMARY KEY, no DB
--    default. cuid values are generated by the application/Prisma
--    client before INSERT; no database sequence is needed.
--
-- 2. String → text throughout. Three fields carry serialised JSON:
--      • User.ownedItems      DEFAULT '[]'
--      • User.accessories     DEFAULT ''
--      • GameSession.questionIds DEFAULT '[]'
--    These are kept as `text` to mirror Prisma's typing. Once data is
--    confirmed clean, consider:
--      ALTER TABLE public."GameSession"
--        ALTER COLUMN "questionIds" TYPE jsonb
--        USING "questionIds"::jsonb;
--    (same for User.ownedItems). Supabase's jsonb operators are then
--    available for richer querying.
--
-- 3. DateTime → timestamptz (time-zone-aware). SQLite stores these as
--    plain text; ensure any migrated data is in ISO-8601 UTC format
--    before inserting.
--
-- 4. Float (LeaderboardEntry.accuracy) → double precision.
--
-- 5. BigInt (User.lifetimeEarnings) → bigint.
--
-- 6. @updatedAt is managed by Prisma client in the app. The trigger
--    `set_updated_at` defined below also enforces it at the DB level,
--    so it stays correct even if rows are updated outside Prisma.
--
-- 7. No Postgres enum types are created — role, gameMode, gameStatus,
--    etc. are stored as text with application-level validation (same
--    behaviour as the SQLite schema).
--
-- 8. ON DELETE CASCADE is preserved where Prisma schema specifies it.
--    Relations without an explicit onDelete keep the Postgres default
--    (RESTRICT / NO ACTION).
--
-- 9. Indexes mirror all @@index and @index directives in the schema.
-- ------------------------------------------------------------------

-- ─── Trigger helper: auto-maintain updatedAt ─────────────────
CREATE OR REPLACE FUNCTION public.set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$;

-- ═══════════════════════════════════════════════════════════════
-- TABLE: User
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."User" (
  id                    text         NOT NULL,
  username              text         NOT NULL,
  "displayName"         text         NOT NULL,
  email                 text,
  "passwordHash"        text         NOT NULL,
  role                  text         NOT NULL DEFAULT 'student',

  -- Stats
  "totalCoins"          integer      NOT NULL DEFAULT 0,
  "totalScore"          integer      NOT NULL DEFAULT 0,
  "gamesPlayed"         integer      NOT NULL DEFAULT 0,
  "gamesWon"            integer      NOT NULL DEFAULT 0,
  "bestStreak"          integer      NOT NULL DEFAULT 0,
  "totalCorrect"        integer      NOT NULL DEFAULT 0,
  "totalIncorrect"      integer      NOT NULL DEFAULT 0,

  -- Platform Expansion: Kit Mode & Tower Climb
  gems                  integer      NOT NULL DEFAULT 0,
  "prestigeLevel"       integer      NOT NULL DEFAULT 0,
  "lifetimeEarnings"    bigint       NOT NULL DEFAULT 0,

  -- Referral & Engagement
  "referralCode"        text,
  "referredBy"          text,
  "referralCount"       integer      NOT NULL DEFAULT 0,
  "lastChallengeDate"   timestamptz,
  "challengesCompleted" integer      NOT NULL DEFAULT 0,

  -- Character Customisation
  "bodyType"            text         NOT NULL DEFAULT 'strong',
  "hairColor"           text         NOT NULL DEFAULT 'red',
  "weaponType"          text         NOT NULL DEFAULT 'hammer',
  accessories           text         NOT NULL DEFAULT '',      -- comma-separated IDs
  "ownedItems"          text         NOT NULL DEFAULT '[]',    -- JSON array (text); see note 2

  -- Campaign & Subscription
  rank                  text         NOT NULL DEFAULT 'Hydrogen',
  "campaignXp"          integer      NOT NULL DEFAULT 0,
  "subscriptionTier"    text         NOT NULL DEFAULT 'free',

  "createdAt"           timestamptz  NOT NULL DEFAULT now(),
  "updatedAt"           timestamptz  NOT NULL DEFAULT now(),

  CONSTRAINT "User_pkey"              PRIMARY KEY (id),
  CONSTRAINT "User_username_key"      UNIQUE (username),
  CONSTRAINT "User_email_key"         UNIQUE (email),
  CONSTRAINT "User_referralCode_key"  UNIQUE ("referralCode")
);

CREATE TRIGGER "User_set_updated_at"
  BEFORE UPDATE ON public."User"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ═══════════════════════════════════════════════════════════════
-- TABLE: UserUpgrade  (Kit Mode enterprises)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."UserUpgrade" (
  id          text        NOT NULL,
  "userId"    text        NOT NULL,
  "upgradeId" text        NOT NULL,   -- e.g. "passive_income_1"
  level       integer     NOT NULL DEFAULT 1,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "UserUpgrade_pkey"                 PRIMARY KEY (id),
  CONSTRAINT "UserUpgrade_userId_upgradeId_key" UNIQUE ("userId", "upgradeId"),
  CONSTRAINT "UserUpgrade_userId_fkey"          FOREIGN KEY ("userId")
    REFERENCES public."User" (id) ON DELETE CASCADE
);

CREATE TRIGGER "UserUpgrade_set_updated_at"
  BEFORE UPDATE ON public."UserUpgrade"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ═══════════════════════════════════════════════════════════════
-- TABLE: UserProgress  (Tower Climb & mode progress)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."UserProgress" (
  id             text        NOT NULL,
  "userId"       text        NOT NULL,
  mode           text        NOT NULL,   -- "tower_climb" | "boss_battle" | etc.
  "highestFloor" integer     NOT NULL DEFAULT 0,
  "bestTime"     integer     NOT NULL DEFAULT 0,  -- seconds
  "totalRuns"    integer     NOT NULL DEFAULT 0,
  "createdAt"    timestamptz NOT NULL DEFAULT now(),
  "updatedAt"    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "UserProgress_pkey"            PRIMARY KEY (id),
  CONSTRAINT "UserProgress_userId_mode_key" UNIQUE ("userId", mode),
  CONSTRAINT "UserProgress_userId_fkey"     FOREIGN KEY ("userId")
    REFERENCES public."User" (id) ON DELETE CASCADE
);

CREATE TRIGGER "UserProgress_set_updated_at"
  BEFORE UPDATE ON public."UserProgress"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ═══════════════════════════════════════════════════════════════
-- TABLE: QuestionSet  (teacher-created sets)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."QuestionSet" (
  id          text        NOT NULL,
  name        text        NOT NULL,
  description text,
  subject     text        NOT NULL DEFAULT 'Chemistry',
  module      text,
  "isPublic"  boolean     NOT NULL DEFAULT false,
  "creatorId" text        NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "QuestionSet_pkey"           PRIMARY KEY (id),
  CONSTRAINT "QuestionSet_creatorId_fkey" FOREIGN KEY ("creatorId")
    REFERENCES public."User" (id)
);

CREATE TRIGGER "QuestionSet_set_updated_at"
  BEFORE UPDATE ON public."QuestionSet"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ═══════════════════════════════════════════════════════════════
-- TABLE: LeaderboardEntry  (persistent, per question set)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."LeaderboardEntry" (
  id              text             NOT NULL,
  "userId"        text             NOT NULL,
  "questionSetId" text,                          -- nullable: global leaderboard when NULL
  "gameMode"      text             NOT NULL,      -- "classic" | "rush" | "survival"
  score           integer          NOT NULL,
  accuracy        double precision NOT NULL,      -- 0.0 – 1.0
  "maxStreak"     integer          NOT NULL,
  "timeTaken"     integer          NOT NULL,      -- total seconds
  "createdAt"     timestamptz      NOT NULL DEFAULT now(),

  CONSTRAINT "LeaderboardEntry_pkey"        PRIMARY KEY (id),
  CONSTRAINT "LeaderboardEntry_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public."User" (id)
);

-- ═══════════════════════════════════════════════════════════════
-- TABLE: Question
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."Question" (
  id              text        NOT NULL,
  question        text        NOT NULL,
  "optionA"       text        NOT NULL,
  "optionB"       text        NOT NULL,
  "optionC"       text        NOT NULL,
  "optionD"       text        NOT NULL,
  "correctAnswer" integer     NOT NULL,   -- 0=A, 1=B, 2=C, 3=D
  subject         text        NOT NULL DEFAULT 'Chemistry',
  topic           text        NOT NULL,
  difficulty      text        NOT NULL,   -- "easy" | "medium" | "hard"
  explanation     text,                   -- shown post-answer (V2)
  "questionSetId" text,
  "createdAt"     timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "Question_pkey"              PRIMARY KEY (id),
  CONSTRAINT "Question_questionSetId_fkey" FOREIGN KEY ("questionSetId")
    REFERENCES public."QuestionSet" (id)
);

-- ═══════════════════════════════════════════════════════════════
-- TABLE: GameSession
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."GameSession" (
  id                  text        NOT NULL,
  "gameCode"          text        NOT NULL,
  "gameMode"          text        NOT NULL DEFAULT 'classic',
  "isMultiplayer"     boolean     NOT NULL DEFAULT false,
  "hostId"            text,
  "userId"            text,
  "questionSetId"     text,
  "totalQuestions"    integer     NOT NULL DEFAULT 10,
  "currentQuestion"   integer     NOT NULL DEFAULT 0,
  "gameStatus"        text        NOT NULL DEFAULT 'waiting', -- "waiting"|"playing"|"finished"
  "questionIds"       text        NOT NULL DEFAULT '[]',      -- JSON array (text); see note 2
  "questionStartedAt" timestamptz,
  score               integer     NOT NULL DEFAULT 0,
  streak              integer     NOT NULL DEFAULT 0,
  "maxStreak"         integer     NOT NULL DEFAULT 0,
  "correctAnswers"    integer     NOT NULL DEFAULT 0,
  "incorrectAnswers"  integer     NOT NULL DEFAULT 0,
  "isCompleted"       boolean     NOT NULL DEFAULT false,
  "startedAt"         timestamptz NOT NULL DEFAULT now(),
  "completedAt"       timestamptz,

  -- Boss Battle fields
  "bossHp"            integer,
  "bossMaxHp"         integer,
  "isCooperative"     boolean     NOT NULL DEFAULT false,

  -- Tower Climb
  "currentFloor"      integer     NOT NULL DEFAULT 0,

  CONSTRAINT "GameSession_pkey"               PRIMARY KEY (id),
  CONSTRAINT "GameSession_gameCode_key"        UNIQUE ("gameCode"),
  CONSTRAINT "GameSession_userId_fkey"         FOREIGN KEY ("userId")
    REFERENCES public."User" (id),
  CONSTRAINT "GameSession_questionSetId_fkey"  FOREIGN KEY ("questionSetId")
    REFERENCES public."QuestionSet" (id)
);

-- ═══════════════════════════════════════════════════════════════
-- TABLE: Player  (multiplayer participant)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."Player" (
  id                text        NOT NULL,
  "gameSessionId"   text        NOT NULL,
  "userId"          text,                    -- NULL for anonymous
  nickname          text        NOT NULL,
  score             integer     NOT NULL DEFAULT 0,
  streak            integer     NOT NULL DEFAULT 0,
  "maxStreak"       integer     NOT NULL DEFAULT 0,
  "correctAnswers"  integer     NOT NULL DEFAULT 0,
  "incorrectAnswers" integer    NOT NULL DEFAULT 0,
  "isHost"          boolean     NOT NULL DEFAULT false,
  "isConnected"     boolean     NOT NULL DEFAULT true,
  "currentAnswer"   integer,
  "answeredAt"      timestamptz,
  "joinedAt"        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "Player_pkey"               PRIMARY KEY (id),
  CONSTRAINT "Player_userId_fkey"        FOREIGN KEY ("userId")
    REFERENCES public."User" (id),
  CONSTRAINT "Player_gameSessionId_fkey" FOREIGN KEY ("gameSessionId")
    REFERENCES public."GameSession" (id) ON DELETE CASCADE
);

-- ═══════════════════════════════════════════════════════════════
-- TABLE: PlayerAnswer
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."PlayerAnswer" (
  id               text        NOT NULL,
  "gameSessionId"  text        NOT NULL,
  "playerId"       text,                    -- NULL for solo sessions
  "questionId"     text        NOT NULL,
  "selectedAnswer" integer     NOT NULL,
  "isCorrect"      boolean     NOT NULL,
  "timeSpent"      integer     NOT NULL,    -- seconds
  "pointsEarned"   integer     NOT NULL,
  "answeredAt"     timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "PlayerAnswer_pkey"               PRIMARY KEY (id),
  CONSTRAINT "PlayerAnswer_gameSessionId_fkey" FOREIGN KEY ("gameSessionId")
    REFERENCES public."GameSession" (id) ON DELETE CASCADE,
  CONSTRAINT "PlayerAnswer_playerId_fkey"      FOREIGN KEY ("playerId")
    REFERENCES public."Player" (id) ON DELETE CASCADE,
  CONSTRAINT "PlayerAnswer_questionId_fkey"    FOREIGN KEY ("questionId")
    REFERENCES public."Question" (id)
);

-- ═══════════════════════════════════════════════════════════════
-- TABLE: CampaignProgress  (chamber completion tracking)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."CampaignProgress" (
  id          text        NOT NULL,
  "userId"    text        NOT NULL,
  "chamberId" text        NOT NULL,   -- e.g. "m1-c1"
  "worldId"   text        NOT NULL,   -- e.g. "module-1"
  completed   boolean     NOT NULL DEFAULT false,
  "bestScore" integer     NOT NULL DEFAULT 0,
  "xpEarned"  integer     NOT NULL DEFAULT 0,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "CampaignProgress_pkey"                 PRIMARY KEY (id),
  CONSTRAINT "CampaignProgress_userId_chamberId_key"  UNIQUE ("userId", "chamberId"),
  CONSTRAINT "CampaignProgress_userId_fkey"          FOREIGN KEY ("userId")
    REFERENCES public."User" (id) ON DELETE CASCADE
);

CREATE TRIGGER "CampaignProgress_set_updated_at"
  BEFORE UPDATE ON public."CampaignProgress"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ═══════════════════════════════════════════════════════════════
-- TABLE: BossAttempt  (campaign boss battle tracking)
-- ═══════════════════════════════════════════════════════════════
CREATE TABLE public."BossAttempt" (
  id            text        NOT NULL,
  "userId"      text        NOT NULL,
  "bossId"      text        NOT NULL,   -- e.g. "acid-baron"
  defeated      boolean     NOT NULL DEFAULT false,
  "damageDealt" integer     NOT NULL DEFAULT 0,
  "createdAt"   timestamptz NOT NULL DEFAULT now(),
  "updatedAt"   timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT "BossAttempt_pkey"        PRIMARY KEY (id),
  CONSTRAINT "BossAttempt_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public."User" (id) ON DELETE CASCADE
);

CREATE TRIGGER "BossAttempt_set_updated_at"
  BEFORE UPDATE ON public."BossAttempt"
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ═══════════════════════════════════════════════════════════════
-- INDEXES  (mirror all @@index / @index directives)
-- ═══════════════════════════════════════════════════════════════

-- User
CREATE INDEX "User_username_idx" ON public."User" (username);
CREATE INDEX "User_email_idx"    ON public."User" (email);

-- UserUpgrade
CREATE INDEX "UserUpgrade_userId_idx" ON public."UserUpgrade" ("userId");

-- UserProgress
CREATE INDEX "UserProgress_userId_idx"            ON public."UserProgress" ("userId");
CREATE INDEX "UserProgress_mode_highestFloor_idx"  ON public."UserProgress" (mode, "highestFloor");

-- QuestionSet
CREATE INDEX "QuestionSet_creatorId_idx" ON public."QuestionSet" ("creatorId");

-- LeaderboardEntry
CREATE INDEX "LeaderboardEntry_questionSetId_gameMode_score_idx"
  ON public."LeaderboardEntry" ("questionSetId", "gameMode", score);
CREATE INDEX "LeaderboardEntry_userId_idx" ON public."LeaderboardEntry" ("userId");

-- Question
CREATE INDEX "Question_questionSetId_idx" ON public."Question" ("questionSetId");
CREATE INDEX "Question_subject_idx"       ON public."Question" (subject);
CREATE INDEX "Question_topic_idx"         ON public."Question" (topic);
CREATE INDEX "Question_difficulty_idx"    ON public."Question" (difficulty);

-- GameSession
CREATE INDEX "GameSession_userId_idx"        ON public."GameSession" ("userId");
CREATE INDEX "GameSession_questionSetId_idx" ON public."GameSession" ("questionSetId");
CREATE INDEX "GameSession_gameStatus_idx"    ON public."GameSession" ("gameStatus");

-- Player
CREATE INDEX "Player_gameSessionId_idx" ON public."Player" ("gameSessionId");
CREATE INDEX "Player_userId_idx"        ON public."Player" ("userId");

-- PlayerAnswer
CREATE INDEX "PlayerAnswer_gameSessionId_idx" ON public."PlayerAnswer" ("gameSessionId");
CREATE INDEX "PlayerAnswer_playerId_idx"      ON public."PlayerAnswer" ("playerId");

-- CampaignProgress
CREATE INDEX "CampaignProgress_userId_idx"  ON public."CampaignProgress" ("userId");
CREATE INDEX "CampaignProgress_worldId_idx" ON public."CampaignProgress" ("worldId");

-- BossAttempt
CREATE INDEX "BossAttempt_userId_idx" ON public."BossAttempt" ("userId");
CREATE INDEX "BossAttempt_bossId_idx" ON public."BossAttempt" ("bossId");
